# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_auto_20170426_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='image_path',
        ),
        migrations.AddField(
            model_name='video',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
